In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [5]:
data=pd.read_csv("CKD.csv")
data

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [6]:
data=pd.get_dummies(data,drop_first=True)
data

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [7]:
data.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [8]:
data["classification_yes"].value_counts()

1    249
0    150
Name: classification_yes, dtype: int64

In [9]:
data.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [10]:
independent=data[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
col=independent.loc[1]

In [11]:
independent.shape

(399, 27)

In [12]:
dependent=data[['classification_yes']]
le=LabelEncoder()
dependent=le.fit_transform(dependent)
dependent

C:\Users\shanm\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0], dtype=int64)

In [13]:
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)
x_train

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
240,60.0,100.0,0.0,3.0,263.0,27.000000,1.300000,135.000000,4.300000,12.700000,...,1,1,0,0,1,1,1,1,0,0
218,57.0,80.0,0.0,0.0,120.0,48.000000,1.600000,137.528754,4.627244,11.300000,...,1,1,0,0,1,1,0,1,0,0
101,42.0,70.0,0.0,0.0,75.0,31.000000,1.200000,141.000000,3.500000,16.500000,...,1,1,0,0,0,0,0,1,0,0
311,66.0,70.0,1.0,0.0,248.0,30.000000,1.700000,138.000000,5.300000,12.518156,...,1,1,0,0,1,1,0,1,0,0
194,55.0,80.0,0.0,0.0,146.0,57.482105,3.077356,137.528754,4.627244,9.800000,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,68.0,70.0,0.0,0.0,98.0,86.000000,4.600000,135.000000,3.400000,9.800000,...,1,1,0,0,1,1,1,0,1,0
192,54.0,90.0,1.0,0.0,150.0,18.000000,1.200000,140.000000,4.200000,12.518156,...,1,0,0,0,0,0,0,0,1,1
117,45.0,80.0,0.0,0.0,107.0,15.000000,1.000000,141.000000,4.200000,11.800000,...,1,0,0,0,0,0,0,1,0,0
47,30.0,80.0,0.0,0.0,89.0,42.000000,0.500000,139.000000,5.000000,16.700000,...,1,1,0,0,0,0,0,1,0,0
172,51.0,60.0,0.0,0.0,129.0,25.000000,1.200000,139.000000,5.000000,17.200000,...,1,1,0,0,0,0,0,1,0,0

In [14]:
sc1=StandardScaler()
x_train=sc1.fit_transform(x_train)
x_test=sc1.transform(x_test)
x_test

array([[-0.37073391, -0.50842064, -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456],
       [ 0.85433499,  1.03002255,  0.94028379, ..., -1.93649167,
        -0.52223297, -0.44519456],
       [ 1.03809533, -0.50842064, -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456],
       ...,
       [-0.24822702,  1.79924415, -0.68384276, ..., -1.93649167,
        -0.52223297, -0.44519456],
       [-0.03431114, -1.27764223,  1.75234707, ...,  0.51639778,
        -0.52223297, -0.44519456],
       [-1.10577525, -1.27764223, -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456]])

In [15]:
param_grid = {"n_neighbors":[3,5,7],"weights":['uniform','distance'],"algorithm":['auto', 'ball_tree', 'kd_tree', 'brute']}


grid = GridSearchCV(KNeighborsClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 

grid.fit(x_train, y_train)

C:\Users\shanm\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 16 concurrent workers.

Fitting 3 folds for each of 24 candidates, totalling 72 fits

[Parallel(n_jobs=-1)]: Done  41 out of  72 | elapsed:    1.3s remaining:    1.0s
[Parallel(n_jobs=-1)]: Done  66 out of  72 | elapsed:    1.3s remaining:    0.0s
[Parallel(n_jobs=-1)]: Done  72 out of  72 | elapsed:    1.4s finished

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='warn', n_jobs=-1,
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [3, 5, 7],
                         'weights': ['uniform', 'distance']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='f1_weighted', verbose=3)

In [17]:
dr=grid.cv_results_
table=pd.DataFrame(dr)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001348,0.000484,0.005850,2.715800e-03,auto,3,uniform,"{'algorithm': 'auto', 'n_neighbors': 3, 'weigh...",0.977654,0.955508,0.977397,0.970159,0.010390,1
1,0.002989,0.001977,0.002074,1.017295e-04,auto,3,distance,"{'algorithm': 'auto', 'n_neighbors': 3, 'weigh...",0.977654,0.955508,0.977397,0.970159,0.010390,1
2,0.001426,0.000509,0.005209,2.332798e-04,auto,5,uniform,"{'algorithm': 'auto', 'n_neighbors': 5, 'weigh...",0.944486,0.955508,0.977397,0.959061,0.013657,13
3,0.000504,0.000410,0.001843,6.331302e-04,auto,5,distance,"{'algorithm': 'auto', 'n_neighbors': 5, 'weigh...",0.955508,0.955508,0.977397,0.962749,0.010299,9
4,0.000514,0.000409,0.002588,4.113537e-04,auto,7,uniform,"{'algorithm': 'auto', 'n_neighbors': 7, 'weigh...",0.911514,0.933485,0.977397,0.940661,0.027348,17
5,0.000667,0.000472,0.001512,3.963486e-04,auto,7,distance,"{'algorithm': 'auto', 'n_neighbors': 7, 'weigh...",0.911514,0.933485,0.977397,0.940661,0.027348,17
6,0.001333,0.001247,0.004707,2.385453e-04,ball_tree,3,uniform,"{'algorithm': 'ball_tree', 'n_neighbors': 3, '...",0.977654,0.955508,0.977397,0.970159,0.010390,1
7,0.001074,0.000099,0.002003,8.182876e-04,ball_tree,3,distance,"{'algorithm': 'ball_tree', 'n_neighbors': 3, '...",0.977654,0.955508,0.977397,0.970159,0.010390,1
8,0.000689,0.000488,0.004533,9.236878e-04,ball_tree,5,uniform,"{'algorithm': 'ball_tree', 'n_neighbors': 5, '...",0.944486,0.955508,0.977397,0.959061,0.013657,13
9,0.000739,0.000530,0.002505,4.110557e-04,ball_tree,5,distance,"{'algorithm': 'ball_tree', 'n_neighbors': 5, '...",0.955508,0.955508,0.977397,0.962749,0.010299,9
10,0.000669,0.000473,0.004875,1.236753e-03,ball_tree,7,uniform,"{'algorithm': 'ball_tree', 'n_neighbors': 7, '...",0.911514,0.933485,0.977397,0.940661,0.027348,17
11,0.000669,0.000473,0.001600,2.957709e-04,ball_tree,7,distance,"{'algorithm': 'ball_tree', 'n_neighbors': 7, '...",0.911514,0.933485,0.977397,0.940661,0.027348,17
12,0.000838,0.000233,0.004842,1.318545e-03,kd_tree,3,uniform,"{'algorithm': 'kd_tree', 'n_neighbors': 3, 'we...",0.977654,0.955508,0.977397,0.970159,0.010390,1
13,0.000333,0.000471,0.002345,2.446413e-04,kd_tree,3,distance,"{'algorithm': 'kd_tree', 'n_neighbors': 3, 'we...",0.977654,0.955508,0.977397,0.970159,0.010390,1
14,0.000334,0.000472,0.003040,4.737576e-04,kd_tree,5,uniform,"{'algorithm': 'kd_tree', 'n_neighbors': 5, 'we...",0.944486,0.955508,0.977397,0.959061,0.013657,13
15,0.000458,0.000648,0.002172,2.491814e-04,kd_tree,5,distance,"{'algorithm': 'kd_tree', 'n_neighbors': 5, 'we...",0.955508,0.955508,0.977397,0.962749,0.010299,9
16,0.001007,0.000008,0.002668,4.706980e-04,kd_tree,7,uniform,"{'algorithm': 'kd_tree', 'n_neighbors': 7, 'we...",0.911514,0.933485,0.977397,0.940661,0.027348,17
17,0.000000,0.000000,0.002000,5.150430e-07,kd_tree,7,distance,"{'algorithm': 'kd_tree', 'n_neighbors': 7, 'we...",0.911514,0.933485,0.977397,0.940661,0.027348,17
18,0.000000,0.000000,0.011061,1.922467e-03,brute,3,uniform,"{'algorithm': 'brute', 'n_neighbors': 3, 'weig...",0.977654,0.955508,0.977397,0.970159,0.010390,1
19,0.000000,0.000000,0.005336,4.737331e-04,brute,3,distance,"{'algorithm': 'brute', 'n_neighbors': 3, 'weig...",0.977654,0.955508,0.977397,0.970159,0.010390,1
20,0.000836,0.000627,0.005482,2.248966e-03,brute,5,uniform,"{'algorithm': 'brute', 'n_neighbors': 5, 'weig...",0.944486,0.955508,0.977397,0.959061,0.013657,13
21,0.000379,0.000536,0.001670,4.700815e-04,brute,5,distance,"{'algorithm': 'brute', 'n_neighbors': 5, 'weig...",0.955508,0.955508,0.977397,0.962749,0.010299,9
22,0.000359,0.000508,0.003700,6.626151e-04,brute,7,uniform,"{'algorithm': 'brute', 'n_neighbors': 7, 'weig...",0.911514,0.933485,0.977397,0.940661,0.027348,17
23,0.000359,0.000508,0.001695,4.900981e-04,brute,7,distance,"{'algorithm': 'brute', 'n_neighbors': 7, 'weig...",0.911514,0.933485,0.977397,0.940661,0.027348,17

In [18]:
grid.best_params_

{'algorithm': 'auto', 'n_neighbors': 3, 'weights': 'uniform'}

In [19]:
grid.best_score_

0.9701591535072297

In [20]:
y_pred=grid.predict(x_test)

In [21]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[51,  0],
       [ 5, 77]], dtype=int64)

In [22]:
cr=classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.91      1.00      0.95        51
           1       1.00      0.94      0.97        82

    accuracy                           0.96       133
   macro avg       0.96      0.97      0.96       133
weighted avg       0.97      0.96      0.96       133

In [23]:
f1=f1_score(y_test,y_pred,average='weighted')
f1

0.9626932787797391

In [24]:
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

0.998804399808704

In [25]:
independent.loc[0]

age               2.000000
bp               76.459948
al                3.000000
su                0.000000
bgr             148.112676
bu               57.482105
sc                3.077356
sod             137.528754
pot               4.627244
hrmo             12.518156
pcv              38.868902
wc             8408.191126
rc                4.705597
sg_b              0.000000
sg_c              1.000000
sg_d              0.000000
sg_e              0.000000
rbc_normal        1.000000
pc_normal         0.000000
pcc_present       0.000000
ba_present        0.000000
htn_yes           0.000000
dm_yes            0.000000
cad_yes           0.000000
appet_yes         1.000000
pe_yes            1.000000
ane_yes           0.000000
Name: 0, dtype: float64

In [26]:
out=sc1.transform([[2.0,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,38.868902,8408.191126,4.705597,0,1,0,0,1,0,0,0,0,0,0,1,1,0]])
out

array([[-3.06588549, -0.01150749,  1.75234707, -0.36409637, -0.01958333,
        -0.05023019, -0.02111956, -0.00417361,  0.02310411,  0.016436  ,
        -0.0161004 ,  0.03813559,  0.03721124, -0.49294082,  1.83320914,
        -0.45124263, -0.13840913,  0.38924947, -1.95866374, -0.34299717,
        -0.23570226, -0.73926425, -0.73926425, -0.29277002,  0.51639778,
         1.91485422, -0.44519456]])

In [27]:
out1=grid.predict(out)
out1

array([1], dtype=int64)